# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CEQUAL_Bathy
                                 A QGIS plugin
 Tools to develope shapefiles defining river network and generate bathymetry input files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-04
        copyright            : (C) 2021 by LimnoTech
        email                : drucinski@limno.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CEQUAL_Bathy class from file CEQUAL_Bathy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cequal_bathy import CEQUAL_Bathy
    return CEQUAL_Bathy(iface)
